/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Carter
 * Created: Jan 4, 2017
 */
/**
*  Initial creation of tables
*/
CREATE TABLE "Clients"
(
    "ClientID" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
    "First Name" VARCHAR (60) NOT NULL,    
    "Last Name" VARCHAR (60) NOT NULL,
    "Status" VARCHAR (120) NOT NULL,
    "Address" VARCHAR (120) NOT NULL,
    "City" VARCHAR (60) NOT NULL,
    "State" VARCHAR (4) NOT NULL,
    "ZIP" INT NOT NULL,
    "Phone" INT,
    "Email" VARCHAR (120),
    CONSTRAINT "PK_Clients" PRIMARY KEY  ("ClientID")
);

CREATE TABLE "Interactions"
(
    "EventID" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
    "Client" INT NOT NULL,    
    "User" INT NOT NULL,
    "Interaction Type" VARCHAR(MAX) NOT NULL,
    "Interaction Date" DATE NOT NULL,    
    CONSTRAINT "PK_Interactions" PRIMARY KEY  ("EventID")
);

/**
*  todo:  Add User table.  Add foreign keys and indexes.
*/